export default {
  COLOR_THEME_PRIMARY: '#345feb',
  COLOR_THEME_SECONDARY: '#6b6b6b',
  COLOR_THEME_ERROR: '#eb343a',
  COLOR_THEME_WARNING: '#e8d138',

  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,

  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
};
